### ISSUE TITLE
Notes for 1.0

### ISSUE THREAD

**Issue by vbawol** [EpochModTeam/EpochCore#5]
- [ ] Rework vehicle flip to make it safer? https://github.com/EpochModTeam/Epoch/issues/80
- [x] I85 elcan visable bug https://github.com/EpochModTeam/Epoch/issues/678
- [ ] More community made assets https://github.com/EpochModTeam/Epoch/issues/507 https://github.com/EpochModTeam/Epoch/issues/593

**Comment by baaljayjay** [comment]
maybe this can visable bug fixed for elcan i have the eye near to elcan
https://drive.google.com/file/d/0B2PXTFaiSMInTlFtUGdGZ2dtbms/view?usp=sharing
I try do complete ut it still takes a bit until I find it out

**Comment by vbawol** [comment]
going to close this and just track everything on the https://github.com/EpochModTeam/Epoch/issues
